### PR TITLE
add missing hysteresis filter option for esp32h2 in gpio

### PR DESCRIPTION
**Pull request by Vollbrecht**
fixes https://github.com/esp-rs/esp-idf-template/issues/193

### CODE REVIEW

**Comment by Vollbrecht** [comment]
@SergioGasquez this should fix the h2 problem

**Comment by Vollbrecht** [comment]
@ivmarkov this fixes nightly clippy + makes h2 buildable again needed for esp-idf-template and stuff

**Comment by ivmarkov** [comment]
Thanks! Any idea why the build fails with ESP IDF `master`?

**Comment by SergioGasquez** [comment]
Is there any scheduled release to have this fix released? @ivmarkov @Vollbrecht

**Comment by ivmarkov** [comment]
Not really. I would like to do an incremental release of the crates in the next couple of weeks, but I wanted to first:
* Check and see how to fix the build for Mac OS (the latest version of the Rust CC crate is the problem there)
* Check and see how to fix the build for ESP IDF `master`. It seems a python env var is missing in latest ESP IDF master

Unfortunately, I don't really have much time right now, to look at any of these two issues. Any help would be appreciated!

**Pull request merged**
