### PR TITLE
add into std::io::Error for EspIOError

### PR DESCRIPTION
**Pull request by zhangzqs**

### CODE REVIEW

**Comment by ivmarkov** [comment]
Why is this necessary?

**Comment by zhangzqs** [comment]
> Why is this necessary?

EspIOError implements the embedded_io::Error trait, and EspIOError also implements std::error::Error in std, so I think it is also reasonable to implement Into<std::io::Error> for EspIOError.

**Comment by ivmarkov** [comment]
> > Why is this necessary?
> 
> EspIOError implements the embedded_io::Error trait, and EspIOError also implements std::error::Error in std, so I think it is also reasonable to implement Into `<std::io::Error>` for EspIOError.



> > Why is this necessary?
> 
> EspIOError implements the embedded_io::Error trait, and EspIOError also implements std::error::Error in std, so I think it is also reasonable to implement Into `<std::io::Error>` for EspIOError.

`embedded_io::Error` and `std::error::Error` are traits, while `std::io::Error` is a struct, so I'm not sure I see the analogy here.
Also, if we go this route, why don't we implement `From<EspError> for std::io::Error` as well?

Isn't here the general wisdom that you should create your own error enums, e.g. 
```rust
enum MyError {
    StdIo(std::io::Error),
    EspIo(EspIOError),
}
```

... either manually, or with the `thiserror` crate?

**Comment by zhangzqs** [comment]
> > > Why is this necessary?
> > 
> > 
> > EspIOError implements the embedded_io::Error trait, and EspIOError also implements std::error::Error in std, so I think it is also reasonable to implement Into `<std::io::Error>` for EspIOError.
> 
> > > Why is this necessary?
> > 
> > 
> > EspIOError implements the embedded_io::Error trait, and EspIOError also implements std::error::Error in std, so I think it is also reasonable to implement Into `<std::io::Error>` for EspIOError.
> 
> `embedded_io::Error` and `std::error::Error` are traits, while `std::io::Error` is a struct, so I'm not sure I see the analogy here. Also, if we go this route, why don't we implement `From<EspError> for std::io::Error` as well?
> 
> Isn't here the general wisdom that you should create your own error enums, e.g.
> 
> ```rust
> enum MyError {
>     StdIo(std::io::Error),
>     EspIo(EspIOError),
> }
> ```
> 
> ... either manually, or with the `thiserror` crate?

In fact, I want to write adapters to adapt the request and response of the http server in esp-idf-svc to std::io::Read and std::io::Write. I write wrapper as follows:
```rust
struct StdReadWrapper<'a, R>
where
    R: embedded_io::Read,
{
    inner: &'a mut R,
}

impl<'a, R, E> std::io::Read for StdReadWrapper<'a, R>
where
    R: embedded_io::Read<Error = E>,
    E: Into<std::io::Error>,
{
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.inner.read(buf).map_err(|e| e.into())
    }
}

struct StdWriteWrapper<'a, W>
where
    W: embedded_io::Write,
{
    inner: &'a mut W,
}

impl<'a, W, E> std::io::Write for StdWriteWrapper<'a, W>
where
    W: embedded_io::Write<Error = E>,
    E: Into<std::io::Error>,
{
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.inner.write(buf).map_err(|e| e.into())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        self.inner.flush().map_err(|e| e.into())
    }
}
```
in such case `E` is EspIOError

**Comment by ivmarkov** [comment]
This would work, does not require `From<EspIOError> for std::io::Error` and would work for **ANY** `embedded_io::Read` trait, not just for traits which happen to implement `E: Into<std::io::Error>` that you are trying to artificially impose on the trait impl:

```rust
impl<'a, R, E> std::io::Read for StdReadWrapper<'a, R>
where
    R: embedded_io::Read<Error = E>,
{
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.inner.read(buf).map_err(|e| std::io::ErrorKind::from(e.kind()).into())
    }
}
```

**Comment by ivmarkov** [comment]
... and is [already implemented](https://github.com/rust-embedded/embedded-hal/blob/master/embedded-io-adapters/src/std.rs#L80) so you don't have to do it.

**Comment by zhangzqs** [comment]
Thanks, you are right

**Pull request closed without merging**
