### PR TITLE
Light sleep wrapper

### PR DESCRIPTION
**Pull request by tcbennun**
Thought it would be nice to wrap light sleep routines.

Work in progress. Suggestions welcome.

Right now it's almost definitely too simple, given that light sleep disrupts peripherals.

### CODE REVIEW

**Comment by ivmarkov** [comment]
Hmmm... if we go for wrapping how about thinking holistically how we wrap the whole ESP32 power management APIs?
Wrapping just a few light sleep routines looks a bit "too little" for me.

**Comment by tcbennun** [comment]
I agree, sorry if this PR is too pre-emptive. I'd like to wrap PM comprehensively but unsure where to start. :)

**Comment by ivmarkov** [comment]
> I agree, sorry if this PR is too pre-emptive. I'd like to wrap PM comprehensively but unsure where to start. :)

Perhaps we can start by studying the [ESP-IDF PM API](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html) as well as the [Sleep API](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html) and then thinking how to map it to Rust in a type-safe way?

**Comment by tcbennun** [comment]
Closing this, will be revisiting more intelligently in due course :)

**Pull request closed without merging**
