### PR TITLE
don't touch pullups on reset while init PinDriver

### PR DESCRIPTION
**Pull request by Vollbrecht**
addresses #343

### CODE REVIEW

**Comment by ivmarkov** [comment]
@Vollbrecht My only concern here is that in the ESP IDF code, they state that they don't leave the pin floating "for powersafe reasons" (whatever that means). Yet here, we would be doing exactly that. Thoughts?

**Comment by Vollbrecht** [comment]
Though from an overall perspective it would only makes sense if the droped value has an owned Pin and not a ref Pin, because in that case we would allow the user to create a new driver, and he would potentially have the same problem again. That might be the case for someone or might not, and its hard to tell for every case. Though overall definitely an opinionated choice here

**Comment by noahbliss** [comment]
Just out of curiosity, if pins are pulled an opinionated direction by esp-idf when they are reset for "power saving reasons", why aren't they pulled an opinionated direction on boot? I only have this problem with pins I have specifically chosen to use/invoke the driver of. 

Would it make sense to, in addition to this fix which fixes the bug on pindriver init, to make "drop" go into an undefined state (no bug, no pull), and add something like "drop_into_pullup" and "drop_into_pulldown" as other means of destruction?

**Comment by ivmarkov** [comment]
@Vollbrecht Would you be willing to resolve the conflict so that we can merge this? (I think conflicts are due to the removal of the `riscv-ulp-hal` feature.)

**Comment by ivmarkov** [comment]
Looks great, thanks!

**Pull request merged**
