### PR TITLE
Correct endianness of RMT signal in neopixel example

### PR DESCRIPTION
**Pull request by musdom**
Bits were sent reversed, which worked for 0xff but not at smaller values to dim the LED. Also added rainbow example using a hsv function.

### CODE REVIEW

**Comment by ivmarkov** [comment]
Thanks!

**Comment by ivmarkov** [comment]
@musdom  You need to fix the formatting though, if you could do that?

**Comment by musdom** [comment]
@ivmarkov could be because I copy pasted code into github editor from vscode. This time I ran it through cargo fmt. Is it better? Thanks

**Comment by musdom** [comment]
Wait let me fix the build failures

**Comment by ivmarkov** [comment]
The problem is that from within `esp-idf-hal` you cannot use, or depend on `esp-idf-svc`, as `esp-idf-svc` itself depends on `esp-idf-hal`. Just replace all logging code with simple `println!` as all other examples do.

**Comment by musdom** [comment]
Ok I actually cloned my fork of the repo and got the patch built, which is something I should've done in the first place :x My bad!

**Pull request merged**
