### PR TITLE
spi/adc_st7789_example

### PR DESCRIPTION
**Pull request by monacoprinsen**
Added an SPI example, drawing an image on the ST7789 screen.

### CODE REVIEW

**Comment by monacoprinsen** [comment]
Added ADC examples

**Comment by ivmarkov** [comment]
@monacoprinsen I think it would be great to have an ADC example! Ideally though, examples should be tiny and targeted to demoing *just one feature*. So I think it would actually be beneficial if you *remove* the st7789 aspects from this example. (Or create *another* example, that is only demonstrating how to write on an *st7789* screen.)

The other thing is, would it be possible to update the example so that it follows the latest changes to the `master` branch? There were quite a few of those, but the ADC driver is mostly intact, modulo some renames here and there?

**Comment by monacoprinsen** [comment]
@ivmarkov thanks for the input.
I have added 3 examples:
Simple adc example
St7789 adc example 
St7789 spi example

If you prefer that I remove the St7789 examples I can do that.

Should work to update to the latest branch, will do that.

**Comment by ivmarkov** [comment]
@monacoprinsen The "St7789 adc" example we should remove, the other two we keep.
Can you please also update the examples to be compatible with latest `master`? They are currently failing the `cargo fmt` but I looked briefly at them, and they are not based on `master`.

**Comment by monacoprinsen** [comment]
@ivmarkov now it should be up to date.

**Comment by ivmarkov** [comment]
> @ivmarkov now it should be up to date.

Can you make sure that the CI checks pass successfully on your changes? I.e. `cargo fmt`, `cargo clippy` and the subsequent actual build. Otherwise, merging your changes will immediately break CI and I need to immediately follow up with fixes of your just merged code.

**Comment by monacoprinsen** [comment]
Will do

**Comment by monacoprinsen** [comment]
@ivmarkov sorry for the delay.... It should be ok now.

**Comment by ivmarkov** [comment]
> @ivmarkov sorry for the delay.... It should be ok now.

Compile fails.

**Comment by monacoprinsen** [comment]
@ivmarkov ok will look into that.

**Comment by ivmarkov** [comment]
The path to the ferris image seems incorrect?

**Comment by monacoprinsen** [comment]
@ivmarkov thanks, adjusted it!
Sorry for the mess, hopefully next contribution will be a little cleaner.

**Comment by ivmarkov** [comment]
Thank you!

**Pull request merged**
