### PR TITLE
Documentation and API adjustments for I2S

### PR DESCRIPTION
**Pull request by dacut**
This fixes a number of usability issues identified by https://github.com/kyrias around the I2S driver and fixes a bug in ESP-IDF around PDM mode stereo vs. mono mode on ESP-C3/-C6/-H2 devices.

I've added documentation around frame formats and adjusted the API around DMA buffering to reflect my now better understanding of what those parameters do.

### CODE REVIEW

**Comment by dacut** [comment]
Keeping in draft for now. This will probably go rebased against master after https://github.com/esp-rs/esp-idf-hal/pull/279 is merged.

**Comment by ivmarkov** [comment]
@dacut I suggest you rebase this PR against the `async-drivers` branch as then I can merge it directly there. Currently it has conflicts, which - I suppose - are due to the fact that you did the changes on top of the `master` branch instead of on top of the `async-drivers` branch, even if the PR is against the `async-drivers` branch?

**Comment by dacut** [comment]
Nope, done against the earlier async-drivers branch. I think this is due to the new pushes; don't worry, there's a reason I've been keeping this in draft state.

I don't have time to look at it until Friday, unfortunately.  Too many things on my plate at the moment.

**Comment by ivmarkov** [comment]
Np, take your time. I don't have time to resume my work on the `async-drivers` branch until next week either.

**Comment by ivmarkov** [comment]
@dacut the `async-drivers` branch is merged since some time. Would you like to rebase your changes against latest mainline?

**Comment by dacut** [comment]
@ivmarkov This is on my to-do list. Need to unbury myself from another task before I can get to this. Thanks!

**Pull request closed without merging**
