### PR TITLE
Fix timer and gpio config for ESP IDF 4.4.x

### PR DESCRIPTION
**Pull request by ivmarkov**
Timer & GPIO configs are both broken for ESP IDF 4.4 and the `riscv32imac-esp-espidf` target.

### CODE REVIEW

**Comment by Vollbrecht** [comment]
interesting, though keep in mind that no chip that is using "riscv32imac-esp-espidf" is official supported with ESP-IDF v4.4

**Comment by Vollbrecht** [comment]
In other words i would not build esp-idf v4.4 against a imac target.

**Comment by ivmarkov** [comment]
> interesting, though keep in mind that no chip that is using "riscv32imac-esp-espidf" is official supported with ESP-IDF v4.4

Are you sure? The documentation for 4.4.8 does not list any of the imac chips as a pre-release or anything like that: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/get-started/index.html

**Comment by Vollbrecht** [comment]
> > interesting, though keep in mind that no chip that is using "riscv32imac-esp-espidf" is official supported with ESP-IDF v4.4
> 
> Are you sure? The documentation for 4.4.8 does not list any of the imac chips as a pre-release or anything like that: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/get-started/index.html

What does have 4.4.8 to do here? Here is the "offical" [support list ](https://github.com/espressif/esp-idf?tab=readme-ov-file#esp-idf-release-and-soc-compatibility). Again i would not bother building h2 or c6 against v4 as even if it would compile i am sure non of the drivers would actually work or more often than not produces garbage results.

**Comment by ivmarkov** [comment]
> > > interesting, though keep in mind that no chip that is using "riscv32imac-esp-espidf" is official supported with ESP-IDF v4.4
> > 
> > 
> > Are you sure? The documentation for 4.4.8 does not list any of the imac chips as a pre-release or anything like that: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/get-started/index.html
> 
> What does have 4.4.8 to do here? Here is the "offical" [support list ](https://github.com/espressif/esp-idf?tab=readme-ov-file#esp-idf-release-and-soc-compatibility). Again i would not bother building h2 or c6 against v4 as even if it would compile i am sure non of the drivers would actually work or more often than not produces garbage results.

Agreed. Though it is still easier for me to push this PR (as it seems to build fine now), rather than going now in the `ci.yaml` and `#ifdef`-ing half of the CI code-paths in such a way, that `riscv32imac-esp-espidf` is only built for >= V5.0. But if you want to do this instead and fix the CI - by all means go ahead! :)

If it is not clear, [`esp-idf-svc` also needs to build for `riscv32imac-esp-espidf`](https://github.com/esp-rs/esp-idf-svc/pull/447). But I don't care if it builds for >= 5.0 either.

**Review by Vollbrecht — APPROVED** [review]
In the interest of time and since CI seams to work i am fine as is. Playing with CI can be done later for the `imac` case or when we go start working on the Monorepo.

**Pull request merged**
