### PR TITLE
Add half duplex and 3wire mode support to SPI

### PR DESCRIPTION
**Pull request by peckpeck**
By using a config option to busmaster builder

### CODE REVIEW

**Comment by peckpeck** [comment]
Any comment on this ?

**Comment by Vollbrecht** [comment]
> Any comment on this ?

on first glance looks good, did you try out all modes on hardware? i read that the c3 variant does not really have an halve duplex support. maybe need to test that to confirm, else we can use an #[cfg(not(esp32c3))]

**Comment by ivmarkov** [comment]
@peckpeck Sorry for the delay. The PR is small and clean - if you could only check indeed if half-duplex is supported on the C variants indeed, and `#[cfg()]` it out if not, then I'll merge.

**Comment by peckpeck** [comment]
I don't have a C variant to test on, but the espressif programming guide for esp32 C2 and C3 document those flags too.

**Pull request merged**
